### ISSUE TITLE
Add a data attribute to notebooks/consoles that support debugging.

### ISSUE THREAD

**Issue by afshin** [jupyterlab/debugger#137]
We should use a mechanism like this to make sure that classes we add (for example to support gutter hovers, etc.) are only visible in notebooks and consoles where they are relevant. We could then target them via CSS selectors, e.g.:

```css
[data-jp-debugger='true'] .CodeMirror-gutter-wrapper::after {
  content: '●';
  color: var(--jp-error-color1);
  /* ... */
}
```
